In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","Ali","Ahmed","Fatima"],
    "Age": [23,None,23,30,27],
    "City": ["Hyderabad","Bangalore","Hyderabad","hyderabad","Bengaluru"],
    "Email": ["ali@gmail.com","sara@gmail.com","ali@gmail.com","ahmed@gmail.com",None]
}

df = pd.DataFrame(data)

df

     Name   Age       City            Email
0     Ali  23.0  Hyderabad    ali@gmail.com
1    Sara   NaN  Bangalore   sara@gmail.com
2     Ali  23.0  Hyderabad    ali@gmail.com
3   Ahmed  30.0  hyderabad  ahmed@gmail.com
4  Fatima  27.0  Bengaluru             None

In [4]:
df.to_csv("raw_data.csv", index=False)

In [7]:
df = df.drop_duplicates().copy()

In [10]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [12]:
df["Email"] = df["Email"].fillna("Unknown")

In [14]:
df["City"] = df["City"].replace({
    "hyderabad": "Hyderabad",
    "Bangalore": "Bengaluru"
})

In [15]:
df

     Name        Age       City            Email
0     Ali  23.000000  Hyderabad    ali@gmail.com
1    Sara  26.666667  Bengaluru   sara@gmail.com
3   Ahmed  30.000000  Hyderabad  ahmed@gmail.com
4  Fatima  27.000000  Bengaluru          Unknown

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [17]:
df.to_csv("cleaned_data.csv", index=False)